name: "Kontinuierliche Integration"

on:
  push:
    branches: [ hauptzweig ]
  pull_request:
    branches: [ hauptzweig ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        RUST_BACKTRACE: 1
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run examples
        uses: actions-rs/cargo@v1
        with:
          command: run
